#!/bin/bash -ex

scripts_folder=$(dirname $0)

# Install certstrap
go get -v github.com/square/certstrap

# Place keys and certificates here
depot_path="${scripts_folder}/../certificates"
mkdir -p ${depot_path}

# CA to generate client certs
${scripts_folder}/generate_ca_cert --common-name "postgresCA" --depot-path ${depot_path} --output-file server-ca

# Certificate to use as the server
server_cn="postgres.service.cf.internal"
${scripts_folder}/generate_end_entity_certs --common-name ${server_cn} --ca-name server-ca --depot-path ${depot_path} --output-file server

# Certificates to use as client
client_cns=( "pgother" "pgadmin" )
for client_cn in "${client_cns[@]}"; do
  ${scripts_folder}/generate_end_entity_certs --common-name "${client_cn}" --ca-name server-ca --depot-path "${depot_path}" --output-file "${client_cn}"
  chmod 600 "${depot_path}/${client_cn}.key"
done
